name: initializer
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 5.2.0
  build_resolvers: 2.1.0
  dart_style: 2.2.4
  sqflite: 2.0.2+1

dependencies:
  data:
    path: ../data
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  shared:
    path: ../shared

dev_dependencies:
  dart_code_metrics: 5.1.0
  flutter_lints: 2.0.1
